name: Tencent Cloud OIDC Demo
on: [push]

permissions:
  id-token: write # Required to request the OIDC JWT token
  contents: read  # Required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Tencent Cloud
        uses: everpcpc/tencentcloud-oidc-auth@v1
        with:
          # doc link: https://github.com/marketplace/actions/authenticate-to-tencent-cloud
          # Replace with your CAM Role Resource Name (ARN)
          role-arn: qcs::cam::uin/100033725386:roleName/oidc-readonly-role
          # Replace with your Tencent Cloud Account ID
          oidc-provider-id: github-provider
          audience: sts.cloud.tencent.com 
          region: ap-guangzhou
      - name: Test Login
        run: |
          tencentcloud-cli sts GetCallerIdentity

